---

- name: Update apt sources
  apt:
    update_cache: yes
    cache_valid_time: 3600
  register: apt_update
  until: apt_update|success
  retries: 5
  delay: 2
  when: ansible_os_family == "Debian"
  tags: update

- name: Install Disk Tools
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - parted
    - xfsprogs
  tags: 
    - disk-tools

- name: Create parition
  parted:
    device: /dev/sdc
    number: 1
    state: present

- name: Create filesystem
  filesystem: 
    fstype: ext4 
    dev: /dev/sdc1 
    #opts: "-i size=1024"
    force: yes
  tags:
    - filesystem

- name: Mount /dev/sdc1
  mount:
    path: /media/data_disk
    src: /dev/sdc1
    fstype: ext4
    state: mounted

- name: Create LXC Volume Group
  lvg:
    vg: lxc
    pvs: /dev/sdc1
  when: inventory_hostname | search("controller")

# # Following lines added to remove mounts and partions to enable testing

# # Remove LXC Volume Group 
# - name: Remove LXC Volume Group
#   lvg:
#     vg: lxc
#     state: absent

# # Remove mount from /etc/fstab
# - name: Remove auto mount /dev/sdc1
#   mount:
#     path: /media/data_disk
#     src: /dev/sdc1
#     fstype: xfs
#     state: absent

# # Unmmount existing mounts
# - name: Unmount /dev/sdc1
#   mount:
#     path: /media/data_disk
#     src: /dev/sdc1
#     fstype: xfs
#     state: unmounted

# # Remove all partitions from disk
# - parted:
#     device: /dev/sdc
#     number: 1
#     state: absent