---

- name: Update apt sources
  apt:
    update_cache: yes
    cache_valid_time: 3600
  register: apt_update
  until: apt_update|success
  retries: 5
  delay: 2
  when: ansible_os_family == "Debian"
  tags: update

- name: Create LXC Volume Group
  lvg:
    vg: lxc
    pvs: "{{ data_disk }}"
  when: inventory_hostname | search("controller")


- name: Create Cinder Volume Group
  lvg:
    vg: cinder-volumes
    pvs: "{{ data_disk }}"
  when: inventory_hostname | search("compute")