---
cidr_networks:
  container: 172.29.236.0/24
  tunnel: 172.29.240.0/24
  storage: 172.29.244.0/24

used_ips:
  - 172.29.236.1
  - 172.29.236.100,172.29.236.200
  - 172.29.240.100,172.29.240.200
  - 172.29.244.100,172.29.244.200
  - 172.29.248.100,172.29.248.200

global_overrides:
  internal_lb_vip_address: 172.29.236.102
  external_lb_vip_address: 192.168.100.102
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        group_binds:
          - all_containers
          - hosts
        type: "raw"
        container_bridge: "br-mgmt"
        container_interface: "eth1"
        container_type: "veth"
        ip_from_q: "container"
        is_container_address: true
        is_ssh_address: true
    - network:
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
          - swift_proxy
        type: "raw"
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        container_mtu: "1500"
        ip_from_q: "storage"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        container_mtu: "1500"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "101:200,301:400"
        net_name: "vlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "eth12"
        type: "flat"
        net_name: "flat"


# Level: shared-infra_hosts (required)
shared-infra_hosts:
  controller01:
    ip: 172.29.236.110
  controller02:
    ip: 172.29.236.111
  controller03:
    ip: 172.29.236.112

# Level: repo-infra_hosts (required)
repo-infra_hosts:
  controller01:
    ip: 172.29.236.110
  controller02:
    ip: 172.29.236.111
  controller03:
    ip: 172.29.236.112

# Level: os-infra_hosts (required)
os-infra_hosts:
  controller01:
    ip: 172.29.236.110
  controller02:
    ip: 172.29.236.111
  controller03:
    ip: 172.29.236.112

# Level: identity_hosts (required)
identity_hosts:
  controller01:
    ip: 172.29.236.110
  controller02:
    ip: 172.29.236.111
  controller03:
    ip: 172.29.236.112

# Level: network_hosts (required)
network_hosts:
  controller01:
    ip: 172.29.236.110
  controller02:
    ip: 172.29.236.111
  controller03:
    ip: 172.29.236.112

# Level: compute_hosts (optional)
compute_hosts:
  compute01:
    ip: 172.29.236.113
  compute02:
    ip: 172.29.236.114

# Level: ironic-compute_hosts (optional)

# Level: storage-infra_hosts (required)
storage-infra_hosts:
  controller01:
    ip: 172.29.236.110
  controller02:
    ip: 172.29.236.111
  controller03:
    ip: 172.29.236.112

# Level: storage_hosts (required)
storage_hosts:
  controller01:
    ip: 172.29.236.110

### THINK THIS NEEDS MORE SETINGS FOR LVM ###


# Level: log_hosts (required)
log_hosts:
  controller02:
    ip: 172.29.236.111

# Level: haproxy_hosts (optional)
  lb01:
    ip: 172.29.236.100
   # lb02:
   #   ip: 172.29.236.101