---
cidr_networks:
  container: 172.29.236.0/24
  tunnel: 172.29.240.0/24
  storage: 172.29.244.0/24

used_ips:
  - 172.29.236.1
  - 172.29.236.100,172.29.236.200
  - 172.29.240.100,172.29.240.200
  - 172.29.244.100,172.29.244.200
  - 172.29.248.100,172.29.248.200

global_overrides:
  internal_lb_vip_address: 172.29.236.117
  external_lb_vip_address: 192.168.100.117
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  
  provider_networks:
    - network:
        group_binds:
          - all_containers
          - hosts
        type: "raw"
        container_bridge: "br-mgmt"
        container_interface: "eth1"
        container_type: "veth"
        ip_from_q: "container"
        is_container_address: true
        is_ssh_address: true
    - network:
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
          # Uncomment the next line if using swift with a storage network.
          # - swift_proxy
        type: "raw"
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        container_mtu: "9000"
        ip_from_q: "storage"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        container_mtu: "9000"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "101:200,301:400"
        net_name: "vlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "eth12"
        type: "flat"
        net_name: "flat"


# Shared infrastructure parts
shared-infra_hosts:
  controller01:
    ip: 172.29.236.110
  controller02:
   ip: 172.29.236.111
  controller03:
   ip: 172.29.236.112

# OpenStack Compute infrastructure parts
os-infra_hosts:
  controller01:
    ip: 172.29.236.110
  controller02:
    ip: 172.29.236.111
  controller03:
    ip: 172.29.236.112

# Shared infrastructure parts
shared-infra_hosts:
  controller01:
    ip: 172.29.236.110
  controller02:
    ip: 172.29.236.111
  controller03:
    ip: 172.29.236.112

# OpenStack Compute infrastructure parts
os-infra_hosts:
  controller01:
    ip: 172.29.236.110
  controller02:
    ip: 172.29.236.111
  controller03:
    ip: 172.29.236.112

# OpenStack Storage infrastructure parts
storage-infra_hosts:
  controller01:
    ip: 172.29.236.110
  controller02:
    ip: 172.29.236.111
  controller03:
    ip: 172.29.236.112

# Keystone Identity infrastructure parts
identity_hosts:
  controller01:
    ip: 172.29.236.110
  controller02:
    ip: 172.29.236.111
  controller03:
    ip: 172.29.236.112

# Compute Hosts
compute_hosts:
  compute01:
    ip: 172.29.236.113
  compute02:
    ip: 172.29.236.114

# Cinder Hosts
storage_hosts:
  controller01:
    ip: 172.29.236.110

# Loging Host
log_hosts:
  controller01:
    ip: 172.29.236.110

# Neutron Hosts
network_hosts:
  controller01:
    ip: 172.29.236.110
  controller02:
    ip: 172.29.236.111
  controller03:
    ip: 172.29.236.112

# User defined Repository Hosts, this is an optional group
repo-infra_hosts:
   controller01:
    ip: 172.29.236.110
  controller02:
    ip: 172.29.236.111
  controller03:
    ip: 172.29.236.112

# haproxy_hosts:
   lb1:
     ip: 172.29.236.100
   # lb2:
   #   ip: 172.29.236.101