---

- name: Bootstrap Ansible
  shell: ./scripts/bootstrap-ansible.sh args1 args2
  args:
    chdir: /opt/openstack-ansible
    creates: /opt/ansible_v*
  # environment: 
  #   BOOTSTRAP_OPTS: bootstrap_host_data_disk_device=sdb
  tags: bootstrap-ansible